language: matlab
# Test all MATLAB releases
matlab:
- latest
- R2023a
- R2022b
- R2022a
- R2021b
- R2021a
- R2020b
- R2020a
jobs:
  # Test all licensing endpoints against oldest and newest MATLAB release
  include:
  - matlab: latest
    env: MATHWORKS_LICENSING_ENDPOINT=prod
  - matlab: R2020a
    env: MATHWORKS_LICENSING_ENDPOINT=prod
  - matlab: latest
    env: MATHWORKS_LICENSING_ENDPOINT=stage
  - matlab: R2020a
    env: MATHWORKS_LICENSING_ENDPOINT=stage
  - matlab: latest
    env: MATHWORKS_LICENSING_ENDPOINT=dev
  - matlab: R2020a
    env: MATHWORKS_LICENSING_ENDPOINT=dev
script: matlab -batch 'version, assertSuccess(runtests())'