jobs:
  # Test all licensing endpoints against oldest and newest MATLAB release
  - template: azure-pipelines-template.yml
    parameters:
      
      MATHWORKS_LICENSING_ENDPOINT: ['prod', 'stage', 'dev']
      RELEASE: ['latest', 'R2020a']
      IMAGE: ['ubuntu-latest']
      
  # Test all MATLAB releases against all supported images
  - template: azure-pipelines-template.yml
    parameters:
      MATHWORKS_LICENSING_ENDPOINT: ['prod']
      RELEASE: ['latest', 'R2023a', 'R2022b', 'R2022a', 'R2021b', 'R2021a', 'R2020b', 'R2020a']
      IMAGE: ['ubuntu-20.04', 'ubuntu-18.04']
