version: 2.1

orbs:
  matlab: mathworks/matlab@0

executors:
  ubuntu-2004:
    machine:
      image: ubuntu-2004:202101-01

jobs:
  test-install:
    parameters:
      MATHWORKS_LICENSING_ENDPOINT:
        type: string
        default: prod
      RELEASE:
        type: string
        default: latest
      EXECUTOR:
        type: executor
        default: ubuntu-2004
    executor: <<parameters.EXECUTOR>>
    environment:
      MATHWORKS_LICENSING_ENDPOINT: <<parameters.MATHWORKS_LICENSING_ENDPOINT>>
    steps:
      - checkout
      - matlab/install:
          release: <<parameters.RELEASE>>
      - matlab/run-command:
          command: version
      - matlab/run-tests

workflows:
  # Test all licensing endpoints against oldest and newest MATLAB release
  test-licws:
    jobs:
      - test-install:
          matrix:
            parameters:
              MATHWORKS_LICENSING_ENDPOINT: ['prod', 'stage', 'dev']
              RELEASE: ['latest', 'R2020a']

  # Test all MATLAB releases against all supported executors
  test-releases:
    jobs:
      - test-install:
          matrix:
            parameters:
              RELEASE: ['latest', 'R2022b', 'R2022a', 'R2021b', 'R2021a', 'R2020b', 'R2020a']
              EXECUTOR: ['ubuntu-2004']
